Project/my_project/Home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'Home'

urlpatterns = [
    path('', views.qbList, name='qbList'),
    path('add_qb/', views.add_qb, name='add_qb'),
    path('single_correct_mcq/<name>/', views.SingleCorrectMCQ, name='single_mcq'),
    path('multi_correct_mcq/<name>/', views.MultiCorrectMCQ, name='multicorrect_mcq'),
    path('matchthecolumns/<name>/', views.matchthecolumns, name='matchingtype'),
    path('add_ques/<name>/', views.add_ques, name='add_ques'),
    path('your_paper/', views.your_paper, name='your_paper'),
    path('add_paper/', views.add_paper, name='add_paper'),
    path('detail_qb/<name>/', views.detail_qb, name='detail_qb'),
    path('view_ques/<id>/', views.view_ques, name='view_ques'),
    path('view_ans/<id>/', views.view_ans, name='view_ans'),
    path('upload_qbfile/<name>/', views.upload_qbfile, name='upload_qbfile'),
    # path('rename_qb/<name>/', views.rename_qb, name='rename_qb'),
    path('delete_qb/<name>/', views.delete_qb, name='delete_qb'),
    path('upload_ques_manually/<name>/', views.add_ques_manually, name='add_ques_manually'),
    path('edit_ques/<id>/', views.edit_ques, name='edit_ques'),
    path('upload_ques_by_file/<name>/', views.add_ques_by_file, name='add_ques_by_file'),
    path('paper_detail/<name>/', views.paper_detail, name='paper_detail'),
    path('upload_ques_module/<name>/', views.add_ques_module, name='add_ques_module'),
    path('add_subques/<id>/', views.add_subques, name='add_subques'),
    path('ques_module_detail/<id>/', views.ques_module_detail, name='ques_module_detail'),
    path('view_subques/<id>/', views.view_subques, name='view_subques'),
    path('view_subans/<id>/', views.view_subans, name='view_subans'),
    path('edit_subques/<id>/', views.edit_subques, name='edit_subques'),
    path('pdf/<id>/',views.generate_pdf,name='generate_pdf'),
    path('edit_ques_module/<id>/', views.edit_ques_module, name='edit_ques_module'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/my_project/my_project/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('sign_upusers.urls')),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^accounts/edit/$', views.edit_profile, name='edit'),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('Home.urls')),
]

Project/my_project/Home/forms.py
from django import forms
from .models import Question_Banks_Main, Questions_Main, Question_Module, SubQuestions

class QuestionBankForm(forms.ModelForm):
    class Meta:
        model = Question_Banks_Main
        # fields = ('username', 'name', 'file')
        exclude = ['username', 'file']

class QuestionBankForm2(forms.ModelForm):
    class Meta:
        model = Question_Banks_Main
        # fields = ('username', 'name', 'file')
        exclude = ['username', 'name']

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Questions_Main
        fields = ('statement', 'answer', 'marks', 'difficulty', 'tag')
        # exclude = ['username', 'file']

class CountryForm(forms.Form):
    OPTION = ()
    OPTION2 = ()
    QP_name = forms.CharField(max_length=150)
    Duration = forms.CharField(max_length=150)
    Question_List = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                          choices=OPTION)
    Question_Module_List = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                              choices=OPTION2)

class SingleCorrectForm(forms.Form):

    def __init__(self,*arg, **kwargs):
        super(SingleCorrectForm,self).__init__(*arg,**kwargs)
        self.empty_permitted = False
    
    ANSWER_CHOICES = [
        ("", 'Select'),
        ("A", 'Choice1'),
        ("B", 'Choice2'),
        ("C", 'Choice3'),
        ("D", 'Choice4'),
    ]

    Choice1 = forms.CharField(required=True)
    Choice2 = forms.CharField()
    Choice3 = forms.CharField()
    Choice4 = forms.CharField()
    Answer = forms.CharField(label="Answer",widget=forms.Select(choices=ANSWER_CHOICES ), required = False)

class MatchtheColumnForm(forms.Form):

    def __init__(self,*arg, **kwargs):
        super(MatchtheColumnForm,self).__init__(*arg,**kwargs)
        self.empty_permitted = False
    

    ANSWER_CHOICES = [
        ("", 'Select'),
        ("A", 'A'),
        ("B", 'B'),
        ("C", 'C'),
        ("D", 'D'),
    ]

    Choice1 = forms.CharField()
    Choice2 = forms.CharField()
    Choice3 = forms.CharField()
    Choice4 = forms.CharField()
    Answer1 = forms.CharField(label="Answer1",widget=forms.Select(choices=ANSWER_CHOICES ), required = False)
    Answer2 = forms.CharField(label="Answer2",widget=forms.Select(choices=ANSWER_CHOICES ), required = False)
    Answer3 = forms.CharField(label="Answer3",widget=forms.Select(choices=ANSWER_CHOICES ), required = False)
    Answer4 = forms.CharField(label="Answer4",widget=forms.Select(choices=ANSWER_CHOICES ), required = False)

class MatchtheColumn2Form(forms.Form):

    def __init__(self,*arg, **kwargs):
        super(MatchtheColumn2Form,self).__init__(*arg,**kwargs)
        self.empty_permitted = False
    
    A = forms.CharField()
    B = forms.CharField()
    C = forms.CharField()
    D = forms.CharField()
    


class MultiCorrectForm(forms.Form):
    def __init__(self,*arg, **kwargs):
        super(MultiCorrectForm,self).__init__(*arg,**kwargs)
        self.empty_permitted = False
    
    
    OPTION = (
        ("a", "Choice1"),
        ("b", "Choice2"),
        ("c", "Choice3"),
        ("d", "Choice4"),
    )
    # OPTION2 = ()
    # QP_name = forms.CharField(max_length=150)
    # Duration = forms.CharField(max_length=150)
    Choice1 = forms.CharField()
    Choice2 = forms.CharField()
    Choice3 = forms.CharField()
    Choice4 = forms.CharField()
    Choose_Answers = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                          choices=OPTION, required=False)
    # Question_Module_List = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                            #   choices=OPTION2)

class MCQForm(forms.Form):

    EASY = 'Easy'
    MEDIUM = 'Medium'
    HARD = 'Hard'

    DIFFICULTY_CHOICES = [
        (EASY, 'Easy'),
        (MEDIUM, 'Medium'),
        (HARD, 'Hard'),
    ]

    statement = forms.CharField(max_length=500)
    # Author = forms.CharField()
    marks = forms.IntegerField()
    difficulty = forms.CharField(label="difficulty",widget=forms.Select(choices=DIFFICULTY_CHOICES))
    tag = forms.CharField(max_length=150)

    

class QuestionBankRenameForm(forms.ModelForm):
    class Meta:
        model = Question_Banks_Main
        fields = ('name',)

class QuestionModuleForm(forms.ModelForm):
    class Meta:
        model = Question_Module
        fields = ('statement', 'subquestions')

class SubQuestionForm(forms.ModelForm):
    class Meta:
        model = SubQuestions
        fields = ('statement', 'answer', 'marks', 'difficulty', 'tag')
        # exclude = ['username', 'file']

class Ques_Module_Name_Form(forms.ModelForm):
    class Meta:
        model = Question_Module
        fields = ('statement',)

Project/my_project/Home/views.py
from itertools import chain

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, render_to_response
from django.urls import reverse
from django.template import RequestContext
from django.core.files.storage import FileSystemStorage
from django.template.loader import render_to_string
from django.template.loader import get_template
# from . models import Question_Banks_Main, Questions_Main, created_paper
# from .forms import QuestionBankForm, QuestionBankForm2, QuestionForm, CountryForm, SingleCorrectForm, MCQForm
from django.forms import formset_factory
# from django.shortcuts import render
# from myapp.forms import ArticleForm
from . models import Question_Banks_Main, Questions_Main, created_paper, Question_Module, SubQuestions
from .forms import QuestionBankForm, QuestionBankForm2, QuestionForm, CountryForm, QuestionBankRenameForm, QuestionModuleForm, SubQuestionForm, SingleCorrectForm, MCQForm, MultiCorrectForm, MatchtheColumnForm, MatchtheColumn2Form, Ques_Module_Name_Form

from configparser import ConfigParser 
# from . models import Question_Banks_Main, Questions_Main
# from .forms import QuestionBankForm, QuestionBankForm2, QuestionForm
from .filters import QuestionsFilter, SubQuestionsFilter
from django.http import HttpResponse
from django.views.generic import View
from .utils import render_to_pdf
import os
from django.contrib import messages

# Create your views here.

@login_required
def SingleCorrectMCQ(request, name):
    ArticleFormSet = formset_factory(SingleCorrectForm, extra=2, max_num=1)
    BookFormSet = formset_factory(MCQForm)
    if request.method == 'POST':
        article_formset = ArticleFormSet(request.POST, request.FILES, prefix='articles')
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')
        print(book_formset.is_valid())
        if article_formset.is_valid() and book_formset.is_valid():
            # do something with the cleaned_data on the formsets.

            for data in book_formset.cleaned_data:
                
                qstatement = data['statement']
                qmarks = data['marks']
                qdifficulty = data['difficulty']
                qtag = data['tag']

                statement_final = ""
                statement_final = statement_final + qstatement + "\n" + "\n"
            
        
            for data in article_formset.cleaned_data:

                statement_final = statement_final + "  A) " + data['Choice1'] + "\n"
                statement_final = statement_final + "  B) " + data['Choice2'] + "\n"
                statement_final = statement_final + "  C) " + data['Choice3'] + "\n"
                statement_final = statement_final + "  D) " + data['Choice4'] + "\n"

                qans = data['Answer']

            q = Questions_Main()
            q.statement=statement_final
            q.marks=qmarks
            q.difficulty=qdifficulty
            q.tag=qtag
            q.answer=qans
            q.qtype=2
            q.username=request.user.username
            q.qb_name=name
            q.save()

            return redirect('Home:detail_qb', name=name)            
    else:
        article_formset = ArticleFormSet(prefix='articles')
        book_formset = BookFormSet(prefix='books')
    return render(request, 'single_correct.html', {
        'article_formset': article_formset,
        'book_formset': book_formset,
    })

@login_required
def MultiCorrectMCQ(request, name):
    ArticleFormSet = formset_factory(MultiCorrectForm, extra=2, max_num=1)
    BookFormSet = formset_factory(MCQForm)
    if request.method == 'POST':
        article_formset = ArticleFormSet(request.POST, request.FILES, prefix='articles')
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')
        if article_formset.is_valid() and book_formset.is_valid():
            
            for data in book_formset.cleaned_data:
                
                qstatement = data['statement']
                qmarks = data['marks']
                qdifficulty = data['difficulty']
                qtag = data['tag']

                statement_final = ""
                statement_final = statement_final + qstatement + "\n" + "\n"

            for data in article_formset.cleaned_data:

                statement_final = statement_final + "  A) " + data['Choice1'] + "\n"
                statement_final = statement_final + "  B) " + data['Choice2'] + "\n"
                statement_final = statement_final + "  C) " + data['Choice3'] + "\n"
                statement_final = statement_final + "  D) " + data['Choice4'] + "\n"

                qans = data['Choose_Answers']
                qans_string = ""

                for a in qans:
                    qans_string = qans_string + a + "\n"

            q = Questions_Main()
            q.statement=statement_final
            q.marks=qmarks
            q.difficulty=qdifficulty
            q.tag=qtag
            q.answer=qans_string
            q.qtype=3
            q.username=request.user.username
            q.qb_name=name
            q.save()

            return redirect('Home:detail_qb', name=name)
    else:
        article_formset = ArticleFormSet(prefix='articles')
        book_formset = BookFormSet(prefix='books')
    return render(request, 'multi_correct.html', {
        'article_formset': article_formset,
        'book_formset': book_formset,
    })

@login_required
def matchthecolumns(request, name):
    ArticleFormSet = formset_factory(MatchtheColumnForm, extra=2, max_num=1)
    ArticleFormSet1 = formset_factory(MatchtheColumn2Form, extra=2, max_num=1)
    BookFormSet = formset_factory(MCQForm)
    if request.method == 'POST':
        article_formset = ArticleFormSet(request.POST, request.FILES, prefix='articles')
        article_formset1 = ArticleFormSet1(request.POST, request.FILES, prefix='articles1')
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')
        if article_formset.is_valid() and book_formset.is_valid() and article_formset1.is_valid():
            
            for data in book_formset.cleaned_data:
                
                qstatement = data['statement']
                qmarks = data['marks']
                qdifficulty = data['difficulty']
                qtag = data['tag']

                statement_final = ""
                statement_final = statement_final + qstatement + "\n"
        
            for data in article_formset.cleaned_data:

                statement_final = statement_final + "A) " + data['Choice1'] + "\n"
                statement_final = statement_final + "B) " + data['Choice2'] + "\n"
                statement_final = statement_final + "C) " + data['Choice3'] + "\n"
                statement_final = statement_final + "D) " + data['Choice4'] + "\n"

                qans1 = data['Answer1']
                qans2 = data['Answer2']
                qans3 = data['Answer3']
                qans4 = data['Answer4']

            for data in article_formset1.cleaned_data:

                statement_final = statement_final + "A) " + data['A'] + "\n"
                statement_final = statement_final + "B) " + data['B'] + "\n"
                statement_final = statement_final + "C) " + data['C'] + "\n"
                statement_final = statement_final + "D) " + data['D'] + "\n"


            qans_string=""
            qans_string = qans1 + "\n" + qans2 + "\n" + qans3 + "\n" + qans4 + "\n" 
            
            q = Questions_Main()
            q.statement=statement_final
            q.marks=qmarks
            q.difficulty=qdifficulty
            q.tag=qtag
            q.answer=qans_string
            q.qtype=4
            q.username=request.user.username
            q.qb_name=name
            q.save()

            return redirect('Home:detail_qb', name=name)


    else:
        article_formset1 = ArticleFormSet1(prefix='articles1')
        article_formset = ArticleFormSet(prefix='articles')
        book_formset = BookFormSet(prefix='books')
    return render(request, 'matchcolumns.html', {
        'article_formset': article_formset,
        'article_formset1': article_formset1,
        'book_formset': book_formset,
    })

def qbList(request):
    qb_list = Question_Banks_Main.objects.filter(username=request.user.username).values('name').distinct()
    return render(request, 'home.html', {
        'qb_list': qb_list
    })

@login_required
def your_paper(request):
    paper_list = created_paper.objects.filter(username=request.user.username)
    return render(request, 'see_ques.html', {
        'paper_list': paper_list
    })

@login_required
def add_paper(request):
    if request.method == 'POST':
        form = CountryForm(request.POST)
        qlist = request.POST.getlist('Question_List')
        # print(qlist)
        qmlist = request.POST.getlist('Question_Module_List')
        qp_name = request.POST.get('QP_name')
        qp_duration = request.POST.get('Duration')
        # if form.is_valid():
            # qpaper = form.save(commit=False)
            # qpaper.username = request.user.username
            # qpaper.save()
        # print(qlist)
        # print(request.POST.get('QP_name'))

        repeated = False
        temp = created_paper.objects.filter(username = request.user.username)

        for i in temp:
            if i.name == qp_name:
                repeated=True

        if repeated==False:
            if len(qlist)!=0 or len(qmlist)!=0:
                qp = created_paper()
                qp.name = qp_name
                qp.username = request.user.username
                qp.num_ques = len(qlist)
                qp.num_ques_modules = len(qmlist)
                qp.duration = qp_duration

                ids = ""
                qm_ids=""
                marks_sum = 0

                for i in qlist:
                    id_temp = i
                    # print(id_temp)

Project/my_project/templates/add_qb.html
{% extends 'base.html' %}

{% block title %}Add{% endblock %}

{% block content %}

  <h2 style="text-align: center"><em>Add a New Question Bank</em></h2>
  <div style="text-align:center">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="button6" type="submit"><em>Create</em></button>
    </form>
  </div>


    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}


  <!-- <h2>Add Question Bank</h2>
 <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
     <button type="submit">Upload</button>
  </form> -->

{% endblock %}

Project/my_project/templates/add_ques_by_file.html
{% extends 'base.html' %}

{% block title %}Add{% endblock %}

{% block content %}
  <h2>Add Question</h2>
 <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
     <button type="submit">Next</button>
  </form>
{% endblock %}

Project/my_project/templates/detail_qb.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}

{% block content %}
  <h1 style="text-align:center"><em>Question Bank Details</em></h1>

<span>
     <button class="button button1"><a href="{% url 'Home:qbList' %}"><em>Go To Home</em></a></button>
 </span>

 <span>
     <button class="button button1"><a href="{% url 'Home:upload_qbfile' name=qb_name %}"><em>Add Question via File</em></a></button>
 </span>

 <span>
     <button class="button button1"><a href="{% url 'Home:add_ques' name=qb_name %}"><em>Add Question Manually</em></a></button>
 </span>

 <span>
     <button class="button button1"><a href="{% url 'Home:add_ques_module' name=qb_name %}"><em>Add a Question Module</em></a></button>
 </span>

 <span>
     <button class="button button1"><a href="{% url 'Home:delete_qb' name=qb_name %}"><em>Delete this Question Bank</em></a></button>
 </span>
 <!-- <span>
        <button><a href="{% url 'Home:single_mcq' name=qb_name %}">Single_Choice_MCQ</a></button>
 </span> -->
<br>
<h3 atyle="text-align:center"><em> Question Bank Name: {{ qb_name }} </em></h3> 
<br><br>
<form method="GET">
<div style="text-align:center">
    <button class="buttonbase button3" type="submit"><em>Search<em></button>
</div>
<br>
{{ filter.form.as_p }}

</form>
<br><br>
<h2 style="text-align:center"><em>QUESTIONS</em></h2>
<div class="container">
<table class="users" style="width: 100%">
    <tr>
        <th class="stat" style="padding: 15px"><em>Statement</em></th>
        <th class="ans" style="padding: 15px"><em>Answer</em></th>
        <th class="tag" style="padding: 15px"><em>Tag</em></th>
        <th class="marks" style="padding: 15px"><em>Marks</em></th>
        <th class="diff" style="padding: 15px"><em>Difficulty</em></th>
        <th class="ed" style="padding: 15px"><em>Edit</em></th>
    </tr>
    {% for ques in filter.qs %}
    <tr style="height: 10px"> 
        <td ><div style="white-space: pre-line"><a href="{% url 'Home:view_ques' id=ques.id %}" target="_blank">{{ ques.statement }}</a></div></td>
        <td ><div style="white-space: pre-line"><a href="{% url 'Home:view_ans' id=ques.id %}" target="_blank">{{ ques.answer }}</a></div></td>
        <td style="text-align:center">{{ ques.tag }}</td>
        <td style="text-align:center">{{ ques.marks }}</td>
        <td style="text-align:center">{{ ques.difficulty }}</td>
        <td style="text-align:center"><button class="button5"><a href="{% url 'Home:edit_ques' id=ques.id %}">Edit</a></button></td>
    </tr>
    {% endfor %}
</table>
</div>

<br>
<h2 style="text-align:center"><em>QUESTION MODULES</em></h2>

{% for qm in ques_module_list %}
    <p><a class="four" href="{% url 'Home:ques_module_detail' id=qm.id %}">{{ qm.statement }}</a></p>
{% endfor %}

{% endblock %}

Project/my_project/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}

 <h1 align='center'><em> Welcome {{ user.username }} </em></h1>
  <div align="center">
     <h3 align="center"> <em> Maintain your list of question banks here </em></h3>
     <button class="button button2"><a  href="{% url 'Home:add_qb' %}"><em>Add Question Bank</em></a></button>
      <button class="button button2"><a  href="{% url 'Home:your_paper' %}"><em>See Your Question Papers</em></a></button>
    </div>
    <br>
    <div style="margin-left: 10px; margin-right: 10px; padding: 5px 10px 20px 10px;  background-color: #999966">
      <h2 style="text-align:center"><em> Already Created Question Banks </em></h2> 
        
        {% for qb in qb_list %}

            <div style="background-color: #cccc00;padding: 5px 5px 5px 10px"> <a class= "two" href="{% url 'Home:detail_qb' name=qb.name %}"><em> {{ qb.name }}</em></a></div>
            <br>
              <!-- {{ qb.username }} -->
        {% endfor %}
    </div>
  <br><br><br>
  
  <div style="background-color: #D6AB55">
    <br>
    <div align="center"><span><a class= "four" href="{% url 'logout' %}">Logout</a></span></div>
    
    <p align='center'><a class= "four" href="{% url 'change_password' %}">Change Password</a></p>
    <p align='center'><a class= "four" href="{% url 'edit' %}">Edit Profile</a></p>
    <br>
  </div>

{% else %}
  <p align='center'>Already a User? Login in Here</p>
  <div align="center"><a class='two' href="{% url 'login' %}">LogIn</a></div>
  <p align='center'>New User? Register Here</p>
  <div align="center"><a class='two' href="{% url 'signup' %}">SignUp</a></div>
{% endif %}
{% endblock %}

Project/my_project/templates/paper_detail.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}

{% block content %}
  <h2 style="text-align:center"><em>Paper Details</em></h2>


    <h4><em> Paper Name: {{ paper.name }}</em></h4>
    <h4><em> Marks: {{ paper.marks }} </em></h4>
    <h4><em> Number Of Questions: {{ paper.total_sum_ques }} Questions </em></h4>
    <h4><em> Duration: {{ paper.duration }} </em></h4>


<span>
     <button class="button button1"><a href="{% url 'Home:qbList' %}"><em>Go To Home</em></a></button>
 </span>
<br><br>
<form method="GET">
    <div style="text-align:center">
        <button class="buttonbase button3" type="submit"><em>Search</em></button>
    </div>
    {{ filter.form.as_p }}

</form>

<br>
<h2 style="text-align:center"><em>Questions</em></h2>
<div class="container">
<table class="users" style="width: 100%">
    <tr>
        <th class="stat" style="padding: 15px"><em>Statement</em></th>
        <th class="ans" style="padding: 15px"><em>Answer</em></th>
        <th class="tag" style="padding: 15px"><em>Tag</em></th>
        
        <th class="diff" style="padding: 15px"><em>Difficulty</em></th>
        <th class="marks" style="padding: 15px"><em>Marks</em></th>
    </tr>
    {% for ques in filter.qs %}
    <tr> 
        <td style="padding: 7px"><div style="white-space: pre-line"><a href="{% url 'Home:view_ques' id=ques.id %}" target="_blank"><em>{{ ques.statement }}</em></a></div></td>
        <td style="padding: 7px"><div style="white-space: pre-line"><a href="{% url 'Home:view_ans' id=ques.id %}" target="_blank"><em>{{ ques.answer }}</em></a></div></td>
        <td style="padding: 7px; text-align:center"><em>{{ ques.tag }}</em></td>
        <td style="padding: 7px; text-align:center"><em>{{ ques.difficulty }}</em></td>
        <td style="padding: 7px; text-align:center"><em>{{ ques.marks }}</em></td>
    </tr>
    {% endfor %}
</table>
</div>

<br>

<h2 style="text-align:center"><em>Question Modules</em></h2>

{% for qm in ques_module_list %}
    <p><a class="four" href="{% url 'Home:ques_module_detail' id=qm.id %}"><em>{{ qm.statement }}</em></a></p>
{% endfor %}

<br><br><br><br>
<div style="text-align:center">
     <button class="button button7"><a class="four" href="{% url 'Home:generate_pdf' id=paper.id %}" target="_blank"><em>Export PDF</em></a></button>
 </div>
{% endblock %}

Project/my_project/templates/ques_module_detail.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}

{% block content %}
  <h2 style="text-align:center"><em>Question Module Details</em></h2>

<span>
     <button class="button button1"><a href="{% url 'Home:qbList' %}"><em>Go To Home</em></a></button>
 </span>

<span>
     <button class="button button1"><a href="{% url 'Home:detail_qb' name=qb_name %}"><em>Back To Question Bank Details</em></a></button>
 </span>

<br>
<h3><em>Statement: {{ ques_module.statement }}</em></h3>
<h3><em>Total Marks: {{ ques_module.marks }}</em></h3>
<br>

<span>
     <button class="button button7"><a href="{% url 'Home:edit_ques_module' id=ques_module.id %}"><em>Edit Question Module</em></a></button>
 </span>


<form method="GET">
<div style="text-align:center">
    <button class="buttonbase button3" type="submit"><em>Search</em></button>
</div>
<br>
{{ filter.form.as_p }}

</form>

<br>
<h2 style="text-align:center"><em>QUESTIONS</em></h2>
<div class="container">
<table class="users" style="width: 100%">
    <tr>
        <th class="stat" style="padding: 15px"><em>Statement</em></th>
        <th class="ans" style="padding: 15px"><em>Answer</em></th>
        <th class="tag" style="padding: 15px"><em>Tag</em></th>
        <th class="marks" style="padding: 15px"><em>Marks</em></th>
        <th class="diff" style="padding: 15px"><em>Difficulty</em></th>
        <th class="ed" style="padding: 15px"><em>Edit</em></th>
    </tr>
    {% for ques in filter.qs %}
    <tr>
        <td style="padding: 7px"><div><a href="{% url 'Home:view_subques' id=ques.id %}" target="_blank"><em>{{ ques.statement }}</em></a></div></td>
        <td style="padding: 7px"><div><a href="{% url 'Home:view_subans' id=ques.id %}" target="_blank"><em>{{ ques.answer }}</em></a></div></td>
        <td style="padding: 7px; text-align:center"><em>{{ ques.tag }}</em></td>
        <td style="padding: 7px; text-align:center"><em>{{ ques.marks }}</em></td>
        <td style="padding: 7px; text-align:center"><em>{{ ques.difficulty }}</em></td>
        <td style="padding: 7px; text-align:center"><button class="button5"><a href="{% url 'Home:edit_subques' id=ques.id %}">Edit</a></button></td>
    </tr>
    {% endfor %}
</table>
</div>


{% endblock %}